// Yupoo 货源链接 - 已验证可访问
// 每个细分类：{ labelKey(4语种), url(主链接), backups(备选) }

const SOURCING_DATA = [
  {
    id: 'cat_jerseys',
    labelKey: 'src_jerseys',
    subcategories: [
      { labelKey: 'src_fan_player',
        url: 'https://kuangre.x.yupoo.com/',
        backups: ['https://hongpintiyu.x.yupoo.com/', 'https://1022669895.x.yupoo.com/albums?tab=gallery', 'https://hxltds.x.yupoo.com/', 'https://691578215.x.yupoo.com/'] },
      { labelKey: 'src_thai',
        url: 'https://lingpao2015.x.yupoo.com/',
        backups: ['https://1022669895.x.yupoo.com/albums?tab=gallery'] },
      { labelKey: 'src_retro',
        url: 'https://fugu2055.x.yupoo.com/albums',
        backups: ['https://huiliyuan.x.yupoo.com/albums', 'https://ingsports0828.x.yupoo.com/albums', 'https://baiyue123.x.yupoo.com/albums'] },
      { labelKey: 'src_cold',
        url: 'https://baiyue123.x.yupoo.com/albums',
        backups: ['https://1040.x.yupoo.com/categories', 'https://fugu2055.x.yupoo.com/albums'] },
      { labelKey: 'src_kids_jersey',
        url: 'https://fuli8888.x.yupoo.com/',
        backups: ['https://qyh2944639738qyh.x.yupoo.com/albums', 'https://798a.x.yupoo.com/', 'https://1040.x.yupoo.com/categories'] },
      { labelKey: 'src_baby',
        url: 'https://ting8899.x.yupoo.com/albums/93369804',
        backups: ['https://fuli8888.x.yupoo.com/'] },
      { labelKey: 'src_pants',
        url: 'https://879322886k.x.yupoo.com/',
        backups: ['https://ty-guoji.x.yupoo.com/categories/4152482'] },
      { labelKey: 'src_long_sleeve',
        url: 'https://8-4hgc8lf.x.yupoo.com/albums?tab=gallery',
        backups: ['https://fugu2055.x.yupoo.com/albums'] },
    ],
  },
  {
    id: 'cat_training',
    labelKey: 'src_training',
    subcategories: [
      { labelKey: 'src_train_suit',
        url: 'https://x.yupoo.com/photos/changjiangsports/albums',
        backups: ['https://ax6789.x.yupoo.com/albums?tab=gallery', 'https://aosendi.x.yupoo.com/albums', 'https://aodong888.x.yupoo.com/categories/4063106'] },
      { labelKey: 'src_yoga',
        url: 'https://aodong888.x.yupoo.com/categories/4802218',
        backups: [] },
    ],
  },
  {
    id: 'cat_apparel',
    labelKey: 'src_apparel',
    subcategories: [
      { labelKey: 'src_windbreaker',
        url: 'https://1215795243.x.yupoo.com/',
        backups: ['https://windbreaker168.x.yupoo.com/'] },
      { labelKey: 'src_hoodie',
        url: 'https://ting8899.x.yupoo.com/categories/3729536',
        backups: ['https://1215795243.x.yupoo.com/'] },
      { labelKey: 'src_racing',
        url: 'https://yiyisports2016.x.yupoo.com/categories/3551571',
        backups: ['https://minkang.x.yupoo.com/albums'] },
      { labelKey: 'src_brand_tee',
        url: 'https://jie080801jin.x.yupoo.com/categories/4876500',
        backups: [] },
      { labelKey: 'src_nba',
        url: 'http://nbazhxzdy8888.x.yupoo.com/',
        backups: [] },
      { labelKey: 'src_down',
        url: 'https://nscp.x.yupoo.com/',  // 原 s.wsxc.cn 短链失效，替换为实际店铺
        backups: ['https://heyi3355.x.yupoo.com/categories/5087591', 'https://1215795243.x.yupoo.com/'] },
      { labelKey: 'src_shorts',
        url: 'https://ty-guoji.x.yupoo.com/categories/4152482',
        backups: ['https://jie080801jin.x.yupoo.com/categories/4876500'] },
      { labelKey: 'src_other_apparel',
        url: 'https://hysport.x.yupoo.com/categories',
        backups: ['https://heyi3355.x.yupoo.com/categories/5087591'] },
    ],
  },
  {
    id: 'cat_shoes',
    labelKey: 'src_shoes',
    subcategories: [
      { labelKey: 'src_adult_shoes',
        url: 'https://jsl68.x.yupoo.com/',
        backups: ['https://gz30038.x.yupoo.com/albums'] },
      { labelKey: 'src_football_boots',
        url: 'https://yongyumeimei.x.yupoo.com/albums?tab=gallery',
        backups: ['https://lvguccinike.x.yupoo.com/', 'https://lyck.x.yupoo.com/'] },
      { labelKey: 'src_kids_shoes',
        url: 'https://zhaomin1981.x.yupoo.com/',
        backups: ['https://017017.x.yupoo.com/'] },
    ],
  },
  {
    id: 'cat_accessories',
    labelKey: 'src_accessories',
    subcategories: [
      { labelKey: 'src_football_acc',
        url: 'https://huandong123.x.yupoo.com/categories',
        backups: ['https://meika1.x.yupoo.com/albums/', 'https://x.yupoo.com/photos/changjiangsports/albums'] },
      { labelKey: 'src_hat',
        url: 'https://lin881106.x.yupoo.com/albums',
        backups: [] },
      { labelKey: 'src_glasses',
        url: 'https://pengpaipai.x.yupoo.com/',
        backups: [] },
      { labelKey: 'src_electronics',
        url: 'https://888080.x.yupoo.com/',
        backups: [] },
      { labelKey: 'src_bag',
        url: 'https://pang2017.x.yupoo.com',
        backups: [] },
      { labelKey: 'src_luxury',
        url: 'https://gz30038.x.yupoo.com/albums',
        backups: ['https://jie080801jin.x.yupoo.com/categories/4876500'] },
    ],
  },
]

export default SOURCING_DATA
